db:
  type: mysql
  hostname: 127.0.0.1
  hostport: 3306
  database: go_db
  username: root
  password: bbfpl123

redis:
  hostname: 127.0.0.1
  hostport: 3306

http:
  port: ":8090"

socket:
  port: ":8091"

jwt:
  secret: "123456"